services:
  mariadb-public1-latest:
    mem_limit: 1g
    image: docker.1ms.run/library/mariadb:latest
    container_name: mariadb-public1
    networks:
      - my-network
    ports:
      - "53308:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - /www/dk_project/dk_app/chrelyonly-mariadb/app/data1:/var/lib/mysql


  mariadb-public2-latest:
    mem_limit: 1g
    image: docker.1ms.run/library/mariadb:latest
    container_name: mariadb-public2
    networks:
      - my-network
    ports:
      - "53309:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - /www/dk_project/dk_app/chrelyonly-mariadb/app/data2:/var/lib/mysql

networks:
  my-network:  # 定义自定义网络
    name: my-network         # 可选：自定义网络名称
    driver: bridge  # 使用默认的 bridge 网络驱动
    ipam: # IP 地址管理配置（IP Address Management）
      driver: default           # 使用默认 IPAM 驱动
      config: # 子网配置（可多个）
        - subnet: 172.20.0.0/16     # 子网网段 172.20.0.1 -- 172.20.255.254
          gateway: 172.20.0.1       # 默认网关
          aux_addresses: # 预留 IP 地址
            host1: 172.20.0.2
            host2: 172.20.0.3
