services:
  nacos_chrelyonly:
    mem_limit: 1024m
    image: nacos/nacos-server:latest
    container_name: nacos_chrelyonly
    environment:
      - MODE=standalone
      - NACOS_AUTH_TOKEN=QXl5S0NiYW1wRjlpSjl0dEZmZXJLdzBMZDNhMHBxcFA=
      - NACOS_AUTH_IDENTITY_KEY=chrelyonly
      - NACOS_AUTH_IDENTITY_VALUE=chrelyonly
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.227.130
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=c7fYmBPyhFhBb34R
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_DATABASE_NUM=1
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - my-network

networks:
  my-network:  # 定义自定义网络
    name: my-network         # 可选：自定义网络名称
    driver: bridge  # 使用默认的 bridge 网络驱动
    ipam: # IP 地址管理配置（IP Address Management）
      driver: default           # 使用默认 IPAM 驱动
      config: # 子网配置（可多个）
        - subnet: 172.20.0.0/16     # 子网网段 172.20.0.1 -- 172.20.255.254
          gateway: 172.20.0.1       # 默认网关
          aux_addresses: # 预留 IP 地址
            host1: 172.20.0.2
            host2: 172.20.0.3
