services:
  redis-public1:
    mem_limit: 512m
    image: docker.1ms.run/library/redis
    container_name: redis-public1
    networks:
      - my-network
    ports:
      - "56379:6379"
    volumes:
      - /www/dk_project/dk_app/chrelyonly-redis/app:/app
    command: ["redis-server", "/app/redis1.conf"]

  redis-public2:
    mem_limit: 512m
    image: docker.1ms.run/library/redis
    container_name: redis-public2
    networks:
      - my-network
    ports:
      - "56380:6379"
    volumes:
      - /www/dk_project/dk_app/chrelyonly-redis/app:/app
    command: ["redis-server", "/app/redis2.conf"]


networks:
  my-network:  # 定义自定义网络
    name: my-network         # 可选：自定义网络名称
    driver: bridge  # 使用默认的 bridge 网络驱动
    ipam: # IP 地址管理配置（IP Address Management）
      driver: default           # 使用默认 IPAM 驱动
      config: # 子网配置（可多个）
        - subnet: 172.20.0.0/16     # 子网网段 172.20.0.1 -- 172.20.255.254
          gateway: 172.20.0.1       # 默认网关
          aux_addresses: # 预留 IP 地址
            host1: 172.20.0.2
            host2: 172.20.0.3
