services:
  chrelyonly-docker-ios:
    mem_limit: 2g
    image: ghcr.io/sky22333/hubproxy
    container_name: chrelyonly-docker-ios
    restart: always
    ports:
      - "5000:5000"
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"

    dns:
      - 114.114.114.114
      - 1.1.1.1  # Cloudflare DNS
    networks:
      - my-network

networks:
  my-network:  # 定义自定义网络
    name: my-network         # 可选：自定义网络名称
    driver: bridge  # 使用默认的 bridge 网络驱动
    ipam: # IP 地址管理配置（IP Address Management）
      driver: default           # 使用默认 IPAM 驱动
      config: # 子网配置（可多个）
        - subnet: 172.20.0.0/16     # 子网网段 172.20.0.1 -- 172.20.255.254
          gateway: 172.20.0.1       # 默认网关
          aux_addresses: # 预留 IP 地址
            host1: 172.20.0.2
            host2: 172.20.0.3