services:
  nacos_chrelyonly:  # 服务名称
    image: nacos/nacos-server:v2.5.0
    container_name: nacos_chrelyonly  # 容器名称
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_XMN=128m
    ports:
      - "8848:8848"
      - "9848:9848" # 如果需要 gRPC
      - "9849:9849" # 如果需要 gRPC
      - "7848:7848" # 如果需要 gRPC
    networks:
      - my-network

networks:
  my-network:  # 定义自定义网络
    name: my-network         # 可选：自定义网络名称
    driver: bridge  # 使用默认的 bridge 网络驱动
    ipam: # IP 地址管理配置（IP Address Management）
      driver: default           # 使用默认 IPAM 驱动
      config: # 子网配置（可多个）
        - subnet: 172.20.0.0/16     # 子网网段 172.20.0.1 -- 172.20.255.254
          gateway: 172.20.0.1       # 默认网关
          aux_addresses: # 预留 IP 地址
            host1: 172.20.0.2
            host2: 172.20.0.3
