services:
  chrelyonly_linker:  # 服务名称
    image: docker.1ms.run/snltty/linker-musl
    container_name: chrelyonly_linker  # 容器名称
    restart: always
    privileged: true
    devices:
      - /dev/net/tun
    ports:
      - "1804:1804/tcp"
      - "18000-18010:18000-18010/tcp"
      - "18000-18010:18000-18010/udp"
    tty: true
    stdin_open: true
    networks:
      - my-network

networks:
  my-network:  # 定义自定义网络
    name: my-network         # 可选：自定义网络名称
    driver: bridge  # 使用默认的 bridge 网络驱动
    ipam: # IP 地址管理配置（IP Address Management）
      driver: default           # 使用默认 IPAM 驱动
      config: # 子网配置（可多个）
        - subnet: 172.20.0.0/16     # 子网网段 172.20.0.1 -- 172.20.255.254
          gateway: 172.20.0.1       # 默认网关
          aux_addresses: # 预留 IP 地址
            host1: 172.20.0.2
            host2: 172.20.0.3
